ao/urls.py
from django.urls import path

from ao import views

app_name = 'ao'

urlpatterns = [
    # HOME
    path('', views.index, name='home'),
    # SEARCH
    path('search/', views.search, name='search'),
    # AO
    path('<int:id_ao>/details/', views.ao_details, name='ao'),
    path('add/', views.add_ao, name='add_ao'),
    path('profile/ao/<int:ao_id>/delete/', views.delete_ao, name='delete_ao'),
    path('<int:ao_id>/edit/', views.edit_ao, name='edit_ao'),
    path('<int:ao_id>/edit/date/', views.update_date, name='edit_ao_date'),
    path('<int:ao_id>/devis/send/', views.send_quotation, name='send_quotation'),
    path('<int:ao_id>/devis/<int:devis_id>/details/', views.devis_details, name='devis'),
    # PROJECT
    path('<int:id_ao>/lot/<int:project_id>/', views.project_details, name='project'),
    path('<int:id_ao>/lot/<int:id_project>/edit/', views.edit_project, name='edit_project'),
    path('<int:id_ao>/lot/add/', views.add_project, name='add_project'),
    path('profile/lot/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    # CATEGORIES
    path('category/<int:category_id>/', views.category, name='category'),
    path('category/<cat_name>/<int:sub_category_id>/', views.sub_category, name='sub_category'),
    # CITY
    path('city/<int:city_id>/', views.city, name='city'),
    # PROFILE
    path('company/<int:company_id>/', views.company, name='company'),
    path('profile/<int:profile_id>/', views.profile, name='profile'),
    path('profile/update/', views.profile_settings, name='profile_settings'),
    path('profile/upgrade/', views.be_company, name='be_company'),
    # SAVES
    path('profile/<int:profile_id>/saves/', views.saves, name='saves'),
    path('profile/<int:profile_id>/saves/delete/<int:save_id>/', views.delete_save, name='save_delete'),
    path('profile/<int:profile_id>/saves/add/<int:id>/', views.add_save, name='add_save'),
    # CONTACTED
    path('profile/<int:profile_id>/contacted/delete/<int:contacted_id>/', views.delete_contacted,
         name='contact_delete'),
    path('profile/<int:profile_id>/contacted/', views.contacted, name='contacted'),
    # CONTACT US
    path('contact/', views.contact, name='contact'),
    # NEWSLETTER
    path('newsletter/subscribe/', views.add_newsletter, name='newsletter'),
]

aoProject/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import settings, static

urlpatterns = [
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('ao/', include('ao.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ao/forms.py
from django import forms


class ImportFile(forms.Form):
    upload_cv = forms.FileField(
        required=False,
        widget=forms.FileInput(
            attrs={
                'class': 'uploadButton-input',
                'accept': 'image/*, application/pdf, application/doc'
            }
        )
    )

main_app/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.password_validation import validate_password


class FormUserInscription(forms.ModelForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    password = forms.CharField(widget=forms.PasswordInput())
    confirmer_votre_mot_de_passe = forms.CharField(widget=forms.PasswordInput())
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'password')

    def clean(self):
        print("cleana User")
        cleaned_data = super(FormUserInscription, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirmer_votre_mot_de_passe")

        email = cleaned_data.get('email')
        username = cleaned_data.get('username')

        if email and User.objects.filter(email=email).exclude(username=username).exists():
            self.add_error('email', "Cet E-mail est déjà enregistré.")

        if password != confirm_password:
            self.add_error("password", "Les deux mot de passes ne sont pas identiques.")

        try:
            validate_password(password=password, )
        except forms.ValidationError as e:
            error_message = list(e.messages)
            for error in error_message:
                self.add_error("password", error + "<br>")


CIVILITE_CHOICES = [('Mr', 'Mr'),
                 ('Mme', 'Mme'),
                 ('Mlle', 'Mlle'),
                 ]

class FormProfilInscription(forms.ModelForm):
    PROFILE_CHOICES = [
        ('Vous êtes un professionnel','Vous êtes un professionnel'),
        ('Vous êtes un particulier','Vous êtes un particulier'),
        ('Vous êtes un étudiant', 'Vous êtes un étudiant'),
        ('Vous êtes un journaliste/éditeur', 'Vous êtes un journaliste/éditeur'),
    ]
    votre_profile = forms.ChoiceField(choices=PROFILE_CHOICES)
    civilite = forms.ChoiceField(choices= CIVILITE_CHOICES,widget=forms.RadioSelect())
    autres = forms.CharField(max_length=300,required=False)

    class Meta:
        model = Profil
        fields = ['civilite', 'nom_entreprise', 'adresse_profile', 'adresse_profile2','code_postal', 'ville', 'pays', 'tel',
                  'tel_portable', 'telecopie','website','activite','taille_entreprise','fonction','departement' ]

    def clean(self):
        cleaned_data = super(FormProfilInscription, self).clean()
        activite = cleaned_data.get("activite")
        taille_entreprise = cleaned_data.get("taille_entreprise")
        fonction = cleaned_data.get("fonction")
        departement = cleaned_data.get("departement")
        votre_profil = cleaned_data.get("votre_profile")
        autres = cleaned_data.get("autres")

        print("cleana m3a rassou ...")
        if votre_profil == 'Vous êtes un professionnel' or votre_profil == 'Vous êtes un journaliste/éditeur':
            if activite is None :
                self.add_error("activite", "Ce champ est obligatoire.")
            if taille_entreprise  is None:
                self.add_error("taille_entreprise", "Ce champ est obligatoire.")
            if fonction  is None:
                self.add_error("fonction", "Ce champ est obligatoire.")
            if departement  is None:
                self.add_error("departement", "Ce champ est obligatoire.")
            if activite == "Autres" and autres  is None:
                self.add_error("autres", "En choisissant 'Autres', Ce champ est obligatoire.")


class loginform(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['email', 'password']


class userform(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'email', 'first_name', 'last_name']


class userProfile(forms.ModelForm):
    class Meta:
        model = Profil
        exclude = ['last_logout', 'user']


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = '__all__'


class formConfirmEmail(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email']


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

ao/views.py
import urllib
import json
from datetime import datetime, timedelta
import pytz

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from ao.forms import ImportFile
from ao.models import City, Category, AO, Project, AOUser, Keyword, SubCategory, Company, AOSaves, PSaves, Contact, \
    Review, File, FileProject, ContactMail, Newsletter, Quotation, QuotationLine
from ao.services import send_email
from aoProject import settings
from main_app.models import Profil, Image


def index(request):
    cities = City.objects.all().annotate(count=Count('project')).order_by('-count')[:4]
    aos = AO.objects.all().order_by('-creation_date').filter(date_limit__gte=datetime.now())[:5]
    categories = Category.objects.all()[:8]

    context = {
        'cities': cities,
        'categories': categories,
        'aos': aos,
        'created_offer': AO.objects.all().count(),
        'created_projects': Project.objects.all().count(),
        'pro_count': AOUser.objects.all().count(),
        'auto_cities': City.objects.all().order_by('name'),
        'auto_keywords': Keyword.objects.all().order_by('name')
    }

    return render(request, 'ao/index.html', context)


def ao_details(request, id_ao):
    ao = get_object_or_404(AO, id=id_ao)

    utc = pytz.UTC
    date_now = utc.localize(datetime.now())
    if ao.date_limit < date_now:
        return redirect('ao:home')

    ao.add_view()

    status = False
    profile_ = None
    if request.user.is_authenticated:
        profile_ = Profil.objects.filter(user=request.user)
        if profile_.count() > 0:
            profile_ = profile_[0]
        else:
            profile_ = None

    if request.method == 'POST':
        ''' Begin reCAPTCHA validation '''
        recaptcha_response = request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            'response': recaptcha_response
        }
        data = urllib.parse.urlencode(values).encode()
        req = urllib.request.Request(url, data=data)
        response = urllib.request.urlopen(req)
        result = json.loads(response.read().decode())
        ''' End reCAPTCHA validation '''

        if result['success']:
            form = ImportFile(request.POST, request.FILES)
            if form.is_valid():
                if profile_ is not None:
                    if AOUser.objects.filter(user=profile_).count() > 0:
                        file = form.cleaned_data['upload_cv']
                        number = request.POST.get('number', None)
                        money = request.POST.get('money', None)
                        message = request.POST.get('message', None)
                        company_ = AOUser.objects.get(user=profile_).company
                        contact_ = Contact.objects.create(
                            company=company_,
                            ao=ao,
                            budget=money,
                            days=number,
                            message=message,
                            file=file
                        )
                        contact_.save()
                        send_email(contact_.id, 'appel d\'offre')
                        status = True

    idp = None
    is_company = False
    already = False
    if profile_ is not None:
        idp = profile_.id
        company_ = AOUser.objects.filter(user=profile_)
        if company_.count() > 0:
            company_ = company_[0].company
            is_company = True
            if Contact.objects.filter(company=company_, ao=ao).count() > 0:
                already = True

    ao_company = None
    if AOUser.objects.filter(user=ao.user).count() > 0:
        ao_company = AOUser.objects.filter(user=ao.user)[0].company

    quotations = None
    if profile_ == ao.user:
        quotations = Quotation.objects.all().filter(ao=ao)

    devis_already = False
    if is_company:
        if Quotation.objects.filter(company=company_, ao=ao).count() > 0:
            devis_already = True

    context = {
        'ao': ao,
        'profile_id': idp,
        'form': ImportFile(),
        'status': status,
        'already': already,
        'is_company': is_company,
        'ao_company': ao_company,
        'lines_number': '0123456789',
        'quotations': quotations,
        'devis_already': devis_already
    }

    return render(request, 'ao/ao.html', context)


def add_ao(request):
    if not request.user.is_authenticated:
        return redirect('ao:home')

    profile_ = request.user.profil
    categories = Category.objects.all().order_by('name')
    status = True

    if request.method == 'POST':
        ''' Begin reCAPTCHA validation '''
        recaptcha_response = request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            'response': recaptcha_response
        }
        data = urllib.parse.urlencode(values).encode()
        req = urllib.request.Request(url, data=data)
        response = urllib.request.urlopen(req)
        result = json.loads(response.read().decode())
        ''' End reCAPTCHA validation '''

        if result['success']:
            title = request.POST.get('title', None)
            category_ = request.POST.get('category', None)
            date_limit = request.POST.get('date_limit', None)
            email = request.POST.get('email', None)
            tel = request.POST.get('tel', None)
            days = request.POST.get('days', None)
            content = request.POST.get('content', None)

            if title == '' or category_ == '' or email == '' or tel == '' or content == '':
                return redirect('ao:home')

            if date_limit == '':
                date_limit = datetime.now() + timedelta(days=30)
            if days == '':
                days = None

            category_ = get_object_or_404(Category, id=category_)
            ao = AO.objects.create(
                title=title,
                category=category_,
                date_limit=date_limit,
                contact_mail=email,
                contact_phone=tel,
                time_limit=days,
                user=profile_,
                description=content
            )
            ao.save()

            files = request.FILES.getlist('files')
            for f in files:
                file_ = File.objects.create(file=f)
                ao.files.add(file_)
                ao.save()

            return redirect('ao:add_project', ao.id)

        else:
            status = False

    company_ = None
    if AOUser.objects.filter(user=profile_).count() > 0:
        company_ = AOUser.objects.get(user=profile_).company

    context = {
        'profile': profile_,
        'categories': categories,
        'status': status,
        'company': company_
    }

    return render(request, 'ao/add_ao.html', context)


def add_project(request, id_ao):
    ao = get_object_or_404(AO, id=id_ao)

    if not request.user.is_authenticated or request.user.profil != ao.user:
        return redirect('ao:ao', id_ao)

    user = get_object_or_404(Profil, id=ao.user.id)
    categories = SubCategory.objects.all().filter(category=ao.category).order_by('name')
    cities = City.objects.all().order_by('name')
    status = False
    recaptcha = False

    if request.method == 'POST':
        ''' Begin reCAPTCHA validation '''
        recaptcha_response = request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            'response': recaptcha_response
        }
        data = urllib.parse.urlencode(values).encode()
        req = urllib.request.Request(url, data=data)
        response = urllib.request.urlopen(req)
        result = json.loads(response.read().decode())
        ''' End reCAPTCHA validation '''

        if result['success']:
            title = request.POST.get('title', None)
            budget = request.POST.get('budget', None)
            keywords = request.POST.get('keywords', None)
            description = request.POST.get('content', None)

            project = Project.objects.create(
                ao=ao,
                title=title,
                budget=budget,
                description=description
            )
            project.save()

            cities = request.POST.getlist('city')
            for c in cities:
                c = get_object_or_404(City, id=c)
                project.city.add(c)
                project.save()

            subcategory = request.POST.getlist('subcategory')
            for c in subcategory:
                c = get_object_or_404(SubCategory, id=c)
                project.categories.add(c)
                project.save()

            files = request.FILES.getlist('files')
            for f in files:
                file_ = FileProject.objects.create(file=f)
                project.files.add(file_)
                project.save()

            if keywords is not None:
                keywords = keywords.split(',')
                for k in keywords:
                    if k != '':
                        kw = Keyword.objects.filter(name=k)
                        if kw.count() == 0:
                            kw = Keyword.objects.create(name=k)
                        else:
                            kw = kw[0]
                        project.keywords.add(kw)
                        project.save()

            status = True
        else:
            recaptcha = True

    company_ = None
    if AOUser.objects.filter(user=user).count() > 0:

ao/templates/ao/includes/footer.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/footer-css.css' %}">

<!-- FOOTER -->
    <footer id="footer" style="padding-top: 20px">
        <!-- Top Footer -->
        <div id="top-footer" class="section">
            <!-- CONTAINER -->
            <div class="container">
                <!-- ROW -->
                <div class="row">
                    <!-- Column 1 -->
                    <div class="col-md-4">
                        <!-- footer about -->
                        <div class="footer-widget about-widget">
                            <div class="footer-logo">
                                <a href="#" class="logo" style="width: 250px">
                                    <img src="{% static 'images/logo_ao_min.png' %}" alt="logo">
                                </a>
                                <p>Populo tritani laboramus ex mei, no eum iuvaret ceteros euripidis, ne alia sadipscing mei. Te inciderint cotidieque pro, ei iisque docendi qui.</p>
                            </div>
                        </div>
                        <!-- /footer about -->

                        <!-- footer social -->
                        <div class="footer-widget social-widget">
                            <div class="widget-title">
                                <h3 class="title">Suivez nous</h3>
                            </div>
                            <ul style="padding: 0">
                                <li><a href="#" class="facebook"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#" class="twitter"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#" class="google"><i class="fa fa-google"></i></a></li>
                                <li><a href="#" class="instagram"><i class="fa fa-instagram"></i></a></li>
                                <li><a href="#" class="youtube"><i class="fa fa-youtube"></i></a></li>
                                <li><a href="#" class="rss"><i class="fa fa-rss"></i></a></li>
                            </ul>
                        </div>
                        <!-- /footer social -->

                        <!-- footer subscribe -->
                        <div class="footer-widget subscribe-widget">
                            <div class="widget-title">
                                <h2 class="title">S'abonner à la Newsletter</h2>
                            </div>
                            <form action="" method="POST" role="form" class="formSubscribe" data-url="{% url 'ao:newsletter' %}">
                                {% csrf_token %}
                                <input type="email" name="email" class="input" placeholder="Email:*" maxlength="40" required="" id="id_email" style="margin: 0; border-radius: 0px;">
                                <button class="input-btn" type="button" id="subscribe_submit">S'inscrire</button>
                                <p class="messageNewslatter"></p>
                            </form>

                        </div>
                        <!-- /footer subscribe -->
                    </div>
                    <!-- /Column 1 -->

                    <!-- Column 2 Les plus lus -->
                    <div class="col-md-4">
                        <!-- widget populaires qst -->
                        <div class="widget">
                            <div class="widget-title">
                                <h2 class="title" style="margin-top: 20px">Appels d'offres populaires</h2>
                            </div>
                            {% for ao in popular_aos %}
                                <article class="article widget-article">
                                    <div class="article-img">
                                        <a href="#">
                                            {% if ao.image is None %}
                                                <img style="max-width: 80px; max-height: 51px;" alt="avatar" src="{% static 'images/company-logo-placeholder.png' %}">
                                            {% else %}
                                                <img style="max-width: 80px; max-height: 51px;" alt="avatar" src="{{ ao.image }}">
                                            {% endif %}
                                        </a>
                                    </div>
                                    <div class="article-body">
                                        <h4 class="article-title">
                                            <a href="{% url 'ao:ao' ao.id %}">{{ ao.title|truncatechars:60 }}</a></h4>
                                        <ul class="article-meta">
                                            <li><i class="icon-feather-clock"></i> {{ ao.date_limit|date }}</li>
                                            <li><i class="icon-feather-eye"></i> {{ ao.views }}</li>
                                        </ul>
                                    </div>
                                </article>
                            {% endfor %}
                        </div>
                        <!-- /widget dernières vidéos -->
                    </div>
                    <!-- /Column 2 Les plus lus -->

                    <!-- Column 4 Meilleurs Tags -->
                    <div class="col-md-4">
                        <div class="widget tags-widget">
                            <div class="widget-title">
                                <h2 class="title" style="margin-bottom: 22px; margin-top: 20px">Meilleurs Keywords</h2>
                            </div>
                            <ul>
                                {% for keyword in top_keywords_ao %}
                                    <li>
                                        <a href="javascript:void(0);">{{ keyword }}</a>
                                        <span class="pull-right">{{ keyword.count_p }}</span>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <!-- /Column 4 Meilleurs Tags -->
                </div>
                <!-- /ROW -->
            </div>
            <!-- /CONTAINER -->
        </div>
        <!-- /Top Footer -->

        <!-- Bottom Footer -->
        <div id="bottom-footer" class="section">
            <!-- CONTAINER -->
            <div class="container">
                <!-- ROW -->
                <div class="row">
                    <!-- footer links -->
                    <div class="col-md-6 col-md-push-6">
                       <div class="footer-copyright" style="text-align: left">
                            <span>
                                Copyright &copy;
                                <script>
                                    document.write(new Date().getFullYear());

                                </script>
                                Tous droits réservés | Réalisé par
                                <a href="javascript:void(0)">ESPR</a>
                            </span>
                        </div>


                    </div>
                    <!-- /footer links -->

                    <!-- footer copyright -->
                    <div class="col-md-6 col-md-pull-6">
                        <!--<ul class="footer-links">
                            <li><a href="#">à propos</a></li>
                            <li><a href="#">Contact</a></li>
                            <li><a href="#">Privacy</a></li>
                        </ul>-->
                    </div>
                    <!-- /footer copyright -->
                </div>
                <!-- /ROW -->
            </div>
            <!-- /CONTAINER -->
        </div>
        <!-- /Bottom Footer -->
    </footer>
    <!-- /FOOTER -->

ao/templates/ao/includes/top_nav_fixed.html
{% load staticfiles %}

    <link rel="stylesheet" href="{% static 'main_app/css/main_style.css' %}">

<div class="topnav" id="myTopnav">
    <div class="container">
        <a href="/" class="f-left nav-acceuil nava" id="acceuil" style="padding: 7px 16px;" > Acceuil</a>
        <a href="/qa" class="border-left-beige f-left nav-qa nava" id="" style="padding: 7px 16px;" >Q&A</a>
        <a href="/journal" class="border-left-beige f-left nav-news nava" id="" style="padding: 7px 16px;" >News</a>
        <a href="/e_commerce" class="border-left-beige f-left nav-market nava" id="linkMarketPlace" style="padding: 7px 16px;" >Market Place</a>
        <a href="/E-Learning/" class="border-left-beige f-left .linkELearning nav-learning nava" style="padding: 7px 16px;"   id="linkELearning">E-learning</a>
        <a href="/reseausocial" class="border-left-beige f-left nava" style="padding: 7px 16px;"  id="linkReseauSocial">Réseau social</a>
        <a href="/appelsOffres" class="border-left-beige f-left nava" style="padding: 7px 16px;"  id="linkAppelsOffres">Appels d'offres</a>

        <div class="dropdowncss" id="dropdown1" >
            <button class="dropbtn">Plus
                <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
                <a href="/reseausocial" class="border-left-beige f-left nav-social nava" style="padding: 7px 16px;"  id="linkReseauSocial1">Réseau social</a>
                <a href="/appelsOffres" class="border-left-beige f-left nav-offres nava" style="padding: 7px 16px;" >Appels d'offres</a>
            </div>
        </div>

        <div class="dropdowncss" id="dropdown2" >
            <button class="dropbtn">Plus
                <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
                <a href="/e_commerce" class="border-left-beige f-left nav-market nava" style="padding: 7px 16px;" >Market Place</a>
                <a href="/E-Learning/" class="border-left-beige f-left nav-learning nava" style="padding: 7px 16px;" >E-learning</a>
                <a href="/reseausocial" class="border-left-beige f-left nav-social nava" style="padding: 7px 16px;"  id="linkReseauSocial2">Réseau social</a>
                <a href="/appelsOffres" class="border-left-beige f-left nav-offres nava" style="padding: 7px 16px;" >Appels d'offres</a>
            </div>
        </div>

        {% if user.is_authenticated %}
            <a href="/logout" class=" border-right f-right nava" style="padding: 7px 16px;" ><i class="fa fa-sign-out "></i> Se deconnecter</a>
            <a href="#" class="f-right  nava" style="padding: 7px 16px; text-transform: none; color: white; background-color: #ea4c0f;">Bonjour {{ user.first_name }}</a>
        {% else %}
            <a href="/contactus" class=" border-right f-right nava" style="padding: 7px 16px;" ><i class="fa fa-envelope"></i></a>
            <a href="/login" class="f-right  border-right nava" style="padding: 7px 16px;" ><i class="fa fa-sign-in"></i> Se connecter</a>
            <a href="/signup" class="border-left border-right f-right nava" style="padding: 7px 16px;"  >S'inscrire</a>
        {% endif %}
        <a href="javascript:void(0);" class="icon nava" style="padding: 7px 16px;"  onclick="myFunction()">&#9776;</a>
    </div>
</div>