ao/urls.py
from django.urls import path

from ao import views

app_name = 'ao'

urlpatterns = [
    # HOME
    path('', views.index, name='home'),
    # SEARCH
    path('search/', views.search, name='search'),
    # AO
    path('<int:id_ao>/details/', views.ao_details, name='ao'),
    path('add/', views.add_ao, name='add_ao'),
    path('profile/ao/<int:ao_id>/delete/', views.delete_ao, name='delete_ao'),
    path('<int:ao_id>/edit/', views.edit_ao, name='edit_ao'),
    path('<int:ao_id>/edit/date/', views.update_date, name='edit_ao_date'),
    path('<int:ao_id>/devis/send/', views.send_quotation, name='send_quotation'),
    path('<int:ao_id>/devis/<int:devis_id>/details/', views.devis_details, name='devis'),
    # PROJECT
    path('<int:id_ao>/lot/<int:project_id>/', views.project_details, name='project'),
    path('<int:id_ao>/lot/<int:id_project>/edit/', views.edit_project, name='edit_project'),
    path('<int:id_ao>/lot/add/', views.add_project, name='add_project'),
    path('profile/lot/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    # CATEGORIES
    path('category/<int:category_id>/', views.category, name='category'),
    path('category/<cat_name>/<int:sub_category_id>/', views.sub_category, name='sub_category'),
    # CITY
    path('city/<int:city_id>/', views.city, name='city'),
    # PROFILE
    path('company/<int:company_id>/', views.company, name='company'),
    path('profile/<int:profile_id>/', views.profile, name='profile'),
    path('profile/update/', views.profile_settings, name='profile_settings'),
    path('profile/upgrade/', views.be_company, name='be_company'),
    # SAVES
    path('profile/<int:profile_id>/saves/', views.saves, name='saves'),
    path('profile/<int:profile_id>/saves/delete/<int:save_id>/', views.delete_save, name='save_delete'),
    path('profile/<int:profile_id>/saves/add/<int:id>/', views.add_save, name='add_save'),
    # CONTACTED
    path('profile/<int:profile_id>/contacted/delete/<int:contacted_id>/', views.delete_contacted,
         name='contact_delete'),
    path('profile/<int:profile_id>/contacted/', views.contacted, name='contacted'),
    # CONTACT US
    path('contact/', views.contact, name='contact'),
    # NEWSLETTER
    path('newsletter/subscribe/', views.add_newsletter, name='newsletter'),
]

aoProject/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import settings, static

urlpatterns = [
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('ao/', include('ao.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ao/forms.py
from django import forms


class ImportFile(forms.Form):
    upload_cv = forms.FileField(
        required=False,
        widget=forms.FileInput(
            attrs={
                'class': 'uploadButton-input',
                'accept': 'image/*, application/pdf, application/doc'
            }
        )
    )

ao/views.py
import urllib
import json
from datetime import datetime, timedelta
import pytz

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from ao.forms import ImportFile
from ao.models import City, Category, AO, Project, AOUser, Keyword, SubCategory, Company, AOSaves, PSaves, Contact, \
    Review, File, FileProject, ContactMail, Newsletter, Quotation, QuotationLine
from ao.services import send_email
from aoProject import settings
from main_app.models import Profil, Image


def index(request):
    cities = City.objects.all().annotate(count=Count('project')).order_by('-count')[:4]
    aos = AO.objects.all().order_by('-creation_date').filter(date_limit__gte=datetime.now())[:5]
    categories = Category.objects.all()[:8]

    context = {
        'cities': cities,
        'categories': categories,
        'aos': aos,
        'created_offer': AO.objects.all().count(),
        'created_projects': Project.objects.all().count(),
        'pro_count': AOUser.objects.all().count(),
        'auto_cities': City.objects.all().order_by('name'),
        'auto_keywords': Keyword.objects.all().order_by('name')
    }

    return render(request, 'ao/index.html', context)


def ao_details(request, id_ao):
    ao = get_object_or_404(AO, id=id_ao)

    utc = pytz.UTC
    date_now = utc.localize(datetime.now())
    if ao.date_limit < date_now:
        return redirect('ao:home')

    ao.add_view()

    status = False
    profile_ = None
    if request.user.is_authenticated:
        profile_ = Profil.objects.filter(user=request.user)
        if profile_.count() > 0:
            profile_ = profile_[0]
        else:
            profile_ = None

    if request.method == 'POST':
        ''' Begin reCAPTCHA validation '''
        recaptcha_response = request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            'response': recaptcha_response
        }
        data = urllib.parse.urlencode(values).encode()
        req = urllib.request.Request(url, data=data)
        response = urllib.request.urlopen(req)
        result = json.loads(response.read().decode())
        ''' End reCAPTCHA validation '''

        if result['success']:
            form = ImportFile(request.POST, request.FILES)
            if form.is_valid():
                if profile_ is not None:
                    if AOUser.objects.filter(user=profile_).count() > 0:
                        file = form.cleaned_data['upload_cv']
                        number = request.POST.get('number', None)
                        money = request.POST.get('money', None)
                        message = request.POST.get('message', None)
                        company_ = AOUser.objects.get(user=profile_).company
                        contact_ = Contact.objects.create(
                            company=company_,
                            ao=ao,
                            budget=money,
                            days=number,
                            message=message,
                            file=file
                        )
                        contact_.save()
                        send_email(contact_.id, 'appel d\'offre')
                        status = True

    idp = None
    is_company = False
    already = False
    if profile_ is not None:
        idp = profile_.id
        company_ = AOUser.objects.filter(user=profile_)
        if company_.count() > 0:
            company_ = company_[0].company
            is_company = True
            if Contact.objects.filter(company=company_, ao=ao).count() > 0:
                already = True

    ao_company = None
    if AOUser.objects.filter(user=ao.user).count() > 0:
        ao_company = AOUser.objects.filter(user=ao.user)[0].company

    quotations = None
    if profile_ == ao.user:
        quotations = Quotation.objects.all().filter(ao=ao)

    devis_already = False
    if is_company:
        if Quotation.objects.filter(company=company_, ao=ao).count() > 0:
            devis_already = True

    context = {
        'ao': ao,
        'profile_id': idp,
        'form': ImportFile(),
        'status': status,
        'already': already,
        'is_company': is_company,
        'ao_company': ao_company,
        'lines_number': '0123456789',
        'quotations': quotations,
        'devis_already': devis_already
    }

    return render(request, 'ao/ao.html', context)


def add_ao(request):
    if not request.user.is_authenticated:
        return redirect('ao:home')

    profile_ = request.user.profil
    categories = Category.objects.all().order_by('name')
    status = True

    if request.method == 'POST':
        ''' Begin reCAPTCHA validation '''
        recaptcha_response = request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            'response': recaptcha_response
        }
        data = urllib.parse.urlencode(values).encode()
        req = urllib.request.Request(url, data=data)
        response = urllib.request.urlopen(req)
        result = json.loads(response.read().decode())
        ''' End reCAPTCHA validation '''

        if result['success']:
            title = request.POST.get('title', None)
            category_ = request.POST.get('category', None)
            date_limit = request.POST.get('date_limit', None)
            email = request.POST.get('email', None)
            tel = request.POST.get('tel', None)
            days = request.POST.get('days', None)
            content = request.POST.get('content', None)

            if title == '' or category_ == '' or email == '' or tel == '' or content == '':
                return redirect('ao:home')

            if date_limit == '':
                date_limit = datetime.now() + timedelta(days=30)
            if days == '':
                days = None

            category_ = get_object_or_404(Category, id=category_)
            ao = AO.objects.create(
                title=title,
                category=category_,
                date_limit=date_limit,
                contact_mail=email,
                contact_phone=tel,
                time_limit=days,
                user=profile_,
                description=content
            )
            ao.save()

            files = request.FILES.getlist('files')
            for f in files:
                file_ = File.objects.create(file=f)
                ao.files.add(file_)
                ao.save()

            return redirect('ao:add_project', ao.id)

        else:
            status = False

    company_ = None
    if AOUser.objects.filter(user=profile_).count() > 0:
        company_ = AOUser.objects.get(user=profile_).company

    context = {
        'profile': profile_,
        'categories': categories,
        'status': status,
        'company': company_
    }

    return render(request, 'ao/add_ao.html', context)


def add_project(request, id_ao):
    ao = get_object_or_404(AO, id=id_ao)

    if not request.user.is_authenticated or request.user.profil != ao.user:
        return redirect('ao:ao', id_ao)

    user = get_object_or_404(Profil, id=ao.user.id)
    categories = SubCategory.objects.all().filter(category=ao.category).order_by('name')
    cities = City.objects.all().order_by('name')
    status = False
    recaptcha = False

    if request.method == 'POST':
        ''' Begin reCAPTCHA validation '''
        recaptcha_response = request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            'response': recaptcha_response
        }
        data = urllib.parse.urlencode(values).encode()
        req = urllib.request.Request(url, data=data)
        response = urllib.request.urlopen(req)
        result = json.loads(response.read().decode())
        ''' End reCAPTCHA validation '''

        if result['success']:
            title = request.POST.get('title', None)
            budget = request.POST.get('budget', None)
            keywords = request.POST.get('keywords', None)
            description = request.POST.get('content', None)

            project = Project.objects.create(
                ao=ao,
                title=title,
                budget=budget,
                description=description
            )
            project.save()

            cities = request.POST.getlist('city')
            for c in cities:
                c = get_object_or_404(City, id=c)
                project.city.add(c)
                project.save()

            subcategory = request.POST.getlist('subcategory')
            for c in subcategory:
                c = get_object_or_404(SubCategory, id=c)
                project.categories.add(c)
                project.save()

            files = request.FILES.getlist('files')
            for f in files:
                file_ = FileProject.objects.create(file=f)
                project.files.add(file_)
                project.save()

            if keywords is not None:
                keywords = keywords.split(',')
                for k in keywords:
                    if k != '':
                        kw = Keyword.objects.filter(name=k)
                        if kw.count() == 0:
                            kw = Keyword.objects.create(name=k)
                        else:
                            kw = kw[0]
                        project.keywords.add(kw)
                        project.save()

            status = True
        else:
            recaptcha = True

    company_ = None
    if AOUser.objects.filter(user=user).count() > 0:

ao/templates/ao/add_project.html
{% extends 'ao/base_small.html' %}

{% load static %}

{% block style %}

    <style>
        .simplebar-content{
            background: #fafafa;
        }
    </style>

{% endblock %}

{% block sidebar %}
    <div class="dashboard-sidebar">
		<div class="dashboard-sidebar-inner" data-simplebar>
			<div class="dashboard-nav-container">

				<!-- Responsive Navigation Trigger -->
				<a href="#" class="dashboard-responsive-nav-trigger">
					<span class="hamburger hamburger--collapse" >
						<span class="hamburger-box">
							<span class="hamburger-inner"></span>
						</span>
					</span>
					<span class="trigger-title">Profil Détails</span>
				</a>

				<!-- Navigation -->
				<div class="dashboard-nav">
					<div class="dashboard-nav-inner">

                        {% if company is None %}
                            <div id="profile-details">
                                <div class="header-image">
                                    <a href="{% url 'ao:profile' profile.id %}">
                                        {% if profile.photo_profil.image.url is not None %}
                                            <img src="{{ profile.photo_profil.image.url }}" alt="">
                                        {% else %}
                                            <img src="{% static 'images/company-logo-05.png' %}">
                                        {% endif %}
                                    </a>
                                </div>

                                <div class="header-details">
                                    <h3 style="padding: 25px; text-align: center; padding-bottom: 0;">{{ profile.user.first_name|capfirst }} {{ profile.user.last_name|upper }}</h3>
                                    <h4 style="text-align: center">{{ profile.fonction }}</h4>
                                </div>
                            </div>

                            <ul data-submenu-title="Liens rapides">
                                <li><a href="{% url 'ao:profile' profile.id %}"><i class="icon-material-outline-assignment"></i> Appels d'offres</a></li>
                                <li><a href="{% url 'ao:saves' profile.id %}"><i class="icon-material-outline-star-border"></i> Enregistrement</a></li>
                            </ul>
                        {% else %}
                            <div id="profile-details">
                                <div class="header-image">
                                    <a href="#">
                                        {% if company.logo.url is not None %}
                                            <img src="{{  company.logo.url }}" alt="">
                                        {% else %}
                                            <img src="{% static 'images/company-logo-05.png' %}">
                                        {% endif %}
                                    </a>
                                </div>

                                <div class="header-details">
                                    <h3 style="padding: 25px; text-align: center; padding-bottom: 0;">{{ company.name }}</h3>
                                    <h4 style="text-align: center">{{ company.activity }}</h4>
                                </div>
                            </div>

                            <ul data-submenu-title="Liens rapides">
                                <li><a href="{% url 'ao:profile' profile.id %}"><i class="icon-material-outline-assignment"></i> Appels d'offres</a></li>
                                <li><a href="{% url 'ao:saves' profile.id %}"><i class="icon-material-outline-star-border"></i> Enregistrement</a></li>
                            </ul>
                        {% endif %}
					</div>
				</div>
				<!-- Navigation / End -->

			</div>
		</div>
	</div>
{% endblock %}

{% block content %}

    <!-- Dashboard Headline -->
			<div class="dashboard-headline">
				<h3>Ajouter Lot</h3>

				<!-- Breadcrumbs -->
				<nav id="breadcrumbs" class="dark">
					<ul>
						<li><a href="{% url 'ao:home' %}">Acceuil</a></li>
						<li><a href="#">Profil</a></li>
						<li><a href="{% url 'ao:ao' ao.id %}">AO</a></li>
						<li>Ajouter un lot</li>
					</ul>
				</nav>
			</div>

			<!-- Row -->
			<div class="row">
                <form method="post" enctype="multipart/form-data" id="form-add-project">
                {% csrf_token %}
                <input id="keywords" type="hidden">
				<!-- Dashboard Box -->
				<div class="col-xl-12">
					<div class="dashboard-box margin-top-0">

						<!-- Headline -->
						<div class="headline">
							<h3><i class="icon-feather-folder-plus"></i> Formulaire de soumission d'ajout de lot</h3>
                            <h5>Détail de l'appel offre source :</h5>
                            <h4><strong>Titre : </strong><a href="{% url 'ao:ao' ao.id %}">{{ ao.title }}</a></h4>
                            <h4><strong>Catégorie :</strong> {{ ao.category }}</h4>
                            <h4><strong>Date de fin :</strong>{{ ao.date_limit }}</h4>
						</div>

						<div class="content with-padding padding-bottom-10">
							<div class="row">
								<div class="col-xl-4">
									<div class="submit-field">
										<h5>Titre</h5>
										<input type="text" name="title" required class="with-border" placeholder="ex. Construction d'un terrain...">
									</div>
								</div>

								<div class="col-xl-4">
									<div class="submit-field">
										<h5>Sous Catégorie</h5>
										<select class="selectpicker with-border" multiple data-size="7" required title="Selectionner une Catégorie" name="subcategory">
                                            {% for category in categories %}
                                                <option value="{{ category.id }}">{{ category }}</option>
                                            {% endfor %}
										</select>
									</div>
								</div>

								<div class="col-xl-4">
									<div class="submit-field">
										<h5>Ville</h5>
                                        <select class="selectpicker with-border" multiple data-size="7" required title="Selectionner une Ville" name="city">
                                            {% for city in cities %}
                                                <option value="{{ city.id }}">{{ city }}</option>
                                            {% endfor %}
                                        </select>
									</div>
								</div>

								<div class="col-xl-6">
									<div class="submit-field">
										<h5>Quel est votre budget estimé?</h5>
										<div class="row">
											<div class="col-xl-12">
												<div class="input-with-icon">
													<input class="with-border" name="budget" required type="text" placeholder="ex. 100000">
													<i class="currency">DH</i>
												</div>
											</div>
										</div>
									</div>
								</div>

								<div class="col-xl-6">
									<div class="submit-field">
										<h5>Keywords de recherche <i class="help-icon" data-tippy-placement="right" title="Permet de trouver votre lot plus rapidement, maximum 5"></i></h5>
										<div class="keywords-container">
											<div class="keyword-input-container">
												<input type="text" class="keyword-input with-border" name="keywords" placeholder="Ajouter Keyword" id="placeKeys"/>
												<button type="button" class="keyword-input-button ripple-effect">
                                                    <i class="icon-material-outline-add"></i>
                                                </button>
											</div>
											<div class="keywords-list"><!-- keywords go here --></div>
											<div class="clearfix"></div>
										</div>
									</div>
								</div>

								<div class="col-xl-12">
									<div class="submit-field">
										<h5>Décrivez votre lot</h5>
										<textarea cols="30" rows="5" name="content" required class="with-border"></textarea>
                                        <table>
                                            <tr>
                                                <td>
                                                    <div class="uploadButton margin-top-14">
                                                        <input class="uploadButton-input" type="file" accept="image/*, application/pdf, application/doc" id="upload" name="files" multiple/>
                                                        <label class="uploadButton-button ripple-effect" for="upload">Importer des fichiers</label>
                                                        <span class="uploadButton-file-name">Images ou documents pouvant être utiles pour décrire votre lot</span>
                                                    </div>
                                                </td>
                                                <td>
                                                    <div style="margin-top: 15px; margin-left: 20px">
                                                        <script src='https://www.google.com/recaptcha/api.js'></script>
                                                        <div class="g-recaptcha" style="display: inline-block;" data-sitekey="6LcIOV8UAAAAAO0kQRvjLmlOt7Q08VEubXgfvG6l"></div>
                                                    </div>
                                                </td>
                                            </tr>
                                        </table>
									</div>
								</div>

							</div>
						</div>
					</div>
				</div>

				<div class="col-xl-12">
					<button class="button ripple-effect big margin-top-30" type="submit">
                        <i class="icon-feather-plus"></i> Poster votre lot
                    </button>
				</div>
                </form>

            </div>

{% endblock %}

{% block script %}

    <script>

        {% if status %}
            Snackbar.show({
                text: 'Lot créé avec succès',
            });
        {% endif %}
        {% if recaptcha %}
            Snackbar.show({
                text: 'Veuillez vérifier la recaptcha',
            });
        {% endif %}

        $("#form-add-project").submit(function () {
            var keys = $("#keywords");
            $(".keywords-list .keyword-text").each(function() {
                var val = keys.val();
                val += ',' + $(this).text();
                keys.val(val);
            });
            $("#placeKeys").val(keys.val());
        });

    </script>


{% endblock %}

ao/templates/ao/base_small.html
{% load static %}

<!doctype html>
<html lang="fr">

<head>

<!-- Basic Page Needs
================================================== -->
<title>AO - Ecosysteme BTP</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<!-- CSS
================================================== -->
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/colors/blue.css' %}">
<link rel="stylesheet" href="{% static 'css/custom-style.css' %}">
<link rel="stylesheet" href="{% static 'css/autocomplete.css' %}">

<style>
    .header-notifications-trigger-me, .header-notifications-trigger-me a {
        font-size: 22px;
        color: #333;
        position: relative;
        top: 55%;
        transform: translate3d(0,-50%,0);
    }
    .header-notifications-trigger-me span{
        display: inline-block;
        top: -15px;
        margin-left: -10px;
        font-weight: 700;
        height: 19px;
        width: 19px;
        line-height: 19px;
        text-align: center;
        color: #fff;
        font-size: 11px;
        background-color: #ea4c0f;
        border-radius: 50%;
        position: relative;
    }
</style>

{% block style %}

{% endblock %}

</head>
<body class="gray">

<!-- Wrapper -->
<div id="wrapper">

{% include 'ao/includes/top_nav_fixed.html' %}

<!-- Header Container
================================================== -->
<header id="header-container" class="fullwidth not-sticky">

	<!-- Header -->
	<div id="header">
		<div class="container">

			<!-- Left Side Content -->
			<div class="left-side">

				<!-- Logo -->
				<div id="logo">
					<a href="{% url 'ao:home' %}"><img src="{% static 'images/logo_ao_min.png' %}" alt=""></a>
				</div>

				<!-- Main Navigation -->
				<nav id="navigation">
					<ul id="responsive">
						<li><a href="{% url 'ao:home' %}">Acceuil</a></li>
						<li><a href="{% url 'ao:search' %}">Appels d'offres</a></li>
                        {% if ao_profile is not None %}
                            <li><a href="{% url 'ao:add_ao' %}">Postuler</a></li>
                            <li style="margin-top: 0">
                                <a href="#">Compte</a>
                                <ul class="dropdown-nav">
                                    <li><a href="{% url 'ao:profile' ao_profile.id %}">Profil</a></li>
                                    <li><a href="{% url 'ao:saves' ao_profile.id %}">Enregistrement</a></li>
                                    <li><a href="{% url 'ao:profile_settings' %}">Paramétres</a></li>
                                </ul>
                            </li>
                        {% endif %}
						<li><a href="{% url 'ao:contact' %}">Contacter nous</a></li>
					</ul>
				</nav>
				<div class="clearfix"></div>
				<!-- Main Navigation / End -->

			</div>
			<!-- Left Side Content / End -->

			<!-- Right Side Content / End -->
			<div class="right-side">
				<!--  User Notifications -->
				<div class="header-widget hide-on-mobile">
					<!-- Notifications -->
					<div class="header-notifications">
						<div class="header-notifications-trigger-me">
                            {% if ao_profile is not None %}
							    <a href="{% url 'ao:profile' ao_profile.id %}" title="Appels d'offres">
                                    <i class="icon-feather-briefcase"></i><span>{{ ao_count }}</span></a>
                            {% else %}
                                <a href="javascript:void(0);" title="Appels d'offres">
                                    <i class="icon-feather-briefcase"></i><span>{{ ao_count }}</span></a>
                            {% endif %}
						</div>
					</div>

					<!-- Messages -->
					<div class="header-notifications">
						<div class="header-notifications-trigger-me">
                            {% if ao_profile is not None %}
                                <a href="{% url 'ao:saves' ao_profile.id %}">
                                    <i class="icon-feather-star"></i><span>{{ save_count }}</span></a>
                            {% else %}
                                <a href="javascript:void(0);" title="Enregistrements">
                                    <i class="icon-feather-star"></i><span>{{ save_count }}</span></a>
                            {% endif %}
						</div>
					</div>

				</div>
				<!--  User Notifications / End -->

				<!-- Mobile Navigation Button -->
				<span class="mmenu-trigger">
					<button class="hamburger hamburger--collapse" type="button">
						<span class="hamburger-box">
							<span class="hamburger-inner"></span>
						</span>
					</button>
				</span>

			</div>
			<!-- Right Side Content / End -->
		</div>
	</div>
	<!-- Header / End -->
</header>

<div class="clearfix"></div>
<!-- Header Container / End -->

<!-- Page Content
================================================== -->
<div class="full-page-container">

    {% block sidebar %}

    {% endblock %}

	<!-- Full Page Content -->
	<div class="full-page-content-container" data-simplebar>
		<div class="full-page-content-inner">
            
            {% block content %}
            
            {% endblock %}
            
			<!-- Footer -->
			<div class="small-footer margin-top-15">
				<div class="small-footer-copyrights">
					© 2018 <strong>Ecosysteme-BTP</strong>. Tous les droits sont réservés.
				</div>
				<ul class="footer-social-links">
					<li>
						<a href="#" title="Facebook" data-tippy-placement="top">
							<i class="icon-brand-facebook-f"></i>
						</a>
					</li>
					<li>
						<a href="#" title="Twitter" data-tippy-placement="top">
							<i class="icon-brand-twitter"></i>
						</a>
					</li>
					<li>
						<a href="#" title="Google Plus" data-tippy-placement="top">
							<i class="icon-brand-google-plus-g"></i>
						</a>
					</li>
					<li>
						<a href="#" title="LinkedIn" data-tippy-placement="top">
							<i class="icon-brand-linkedin-in"></i>
						</a>
					</li>
				</ul>
				<div class="clearfix"></div>
			</div>
			<!-- Footer / End -->

		</div>
	</div>
	<!-- Full Page Content / End -->

</div>


</div>
<!-- Wrapper / End -->

<!-- Scripts
================================================== -->
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.0.min.js' %}"></script>
<script src="{% static 'js/mmenu.min.js' %}"></script>
<script src="{% static 'js/tippy.all.min.js' %}"></script>
<script src="{% static 'js/simplebar.min.js' %}"></script>
<script src="{% static 'js/bootstrap-slider.min.js' %}"></script>
<script src="{% static 'js/bootstrap-select.min.js' %}"></script>
<script src="{% static 'js/snackbar.js' %}"></script>
<script src="{% static 'js/clipboard.min.js' %}"></script>
<script src="{% static 'js/counterup.min.js' %}"></script>
<script src="{% static 'js/magnific-popup.min.js' %}"></script>
<script src="{% static 'js/slick.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/autocomplete.js' %}"></script>
<script src="{% static 'js/ajax_functions.js' %}"></script>

<script>
    // Snackbar for user status switcher
    $('#snackbar-user-status label').click(function() {
        Snackbar.show({
            text: 'Your status has been changed!',
            pos: 'bottom-center',
            showAction: false,
            actionText: "Dismiss",
            duration: 3000,
            textColor: '#fff',
            backgroundColor: '#383838'
        });
    });
</script>

{% block script %}

{% endblock %}

</body>

</html>